name: update
on: 
  push:
  schedule:
    - cron: '0 0 1 * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: execute py script # run the run.py to get the latest data
        run: |
         shopt -s globstar
         git clone https://github.com/ProgramComputer/hostsblock.git
         cd **/hostsblock
         make
         cd -
         mkdir -p ABPindo+EasyList
         mkdir -p ABPVNList+EasyList
         mkdir -p Bulgarianlist+EasyList
         mkdir -p DandelionSprout'sNordicFilters+EasyList
         mkdir -p EasyListChina+EasyList
         mkdir -p EasyListCzechandSlovak+EasyList
         mkdir -p EasyListDutch+EasyList
         mkdir -p EasyListGermany+EasyList
         mkdir -p EasyListHebrew+EasyList
         mkdir -p EasyListItaly+EasyList
         mkdir -p EasyListLithuania+EasyList
         mkdir -p EasyListPolish+EasyList
         mkdir -p EasyListPortuguese+EasyList
         mkdir -p EasyListSpanish+EasyList
         mkdir -p IndianList+EasyList
         mkdir -p KoreanList+EasyList
         mkdir -p LatvianList+EasyList
         mkdir -p ListeAR+ListeFR+EasyList
         mkdir -p ListeFR+EasyList
         mkdir -p ROList+EasyList
         mkdir -p RuAdList+EasyList
 
         curl -s "https://easylist-downloads.adblockplus.org/easylist.txt" | ./hostsblock/hostsblock - > hosts
         curl -s "https://easylist-downloads.adblockplus.org/abpindo+easylist.txt" | ./hostsblock/hostsblock - > ./ABPindo+EasyList/hosts
         curl -s "https://easylist-downloads.adblockplus.org/abpvn+easylist.txt" | ./hostsblock/hostsblock - > ./ABPVNList+EasyList/hosts
         curl -s "https://easylist-downloads.adblockplus.org/bulgarian_list+easylist.txt" | ./hostsblock/hostsblock - > ./Bulgarianlist+EasyList/hosts
         curl -s "https://easylist-downloads.adblockplus.org/dandelion_sprouts_nordic_filters+easylist.txt"  | ./hostsblock/hostsblock - > ./DandelionSprout'sNordicFilters+EasyList/hosts
         curl -s "https://easylist-downloads.adblockplus.org/easylistchina+easylist.txt" | ./hostsblock/hostsblock - > ./EasyListChina+EasyList/hosts
         curl -s "https://easylist-downloads.adblockplus.org/easylistczechslovak+easylist.txt" | ./hostsblock/hostsblock - > ./EasyListCzechandSlovak+EasyList/hosts
         curl -s "https://easylist-downloads.adblockplus.org/easylistdutch+easylist.txt" | ./hostsblock/hostsblock - > ./EasyListDutch+EasyList/hosts
         curl -s "https://easylist-downloads.adblockplus.org/easylistgermany+easylist.txt" | ./hostsblock/hostsblock - > ./EasyListGermany+EasyList/hosts
         curl -s "https://easylist-downloads.adblockplus.org/israellist+easylist.txt" | ./hostsblock/hostsblock - > ./EasyListHebrew+EasyList/hosts
         curl -s "https://easylist-downloads.adblockplus.org/easylistitaly+easylist.txt" | ./hostsblock/hostsblock - > ./EasyListItaly+EasyList/hosts
         curl -s "https://easylist-downloads.adblockplus.org/easylistlithuania+easylist.txt" | ./hostsblock/hostsblock - > ./EasyListLithuania+EasyList/hosts
         curl -s "https://easylist-downloads.adblockplus.org/easylistpolish+easylist.txt" | ./hostsblock/hostsblock - >  ./EasyListPolish+EasyList/hosts
         curl -s "https://easylist-downloads.adblockplus.org/easylistportuguese+easylist.txt" | ./hostsblock/hostsblock - >  ./EasyListPortuguese+EasyList/hosts
         curl -s "https://easylist-downloads.adblockplus.org/easylistspanish+easylist.txt" | ./hostsblock/hostsblock - > ./EasyListSpanish+EasyList/hosts
         curl -s "https://easylist-downloads.adblockplus.org/indianlist+easylist.txt" | ./hostsblock/hostsblock - > ./IndianList+EasyList/hosts
         curl -s "https://easylist-downloads.adblockplus.org/koreanlist+easylist.txt" | ./hostsblock/hostsblock - > ./KoreanList+EasyList/hosts
         curl -s "https://easylist-downloads.adblockplus.org/latvianlist+easylist.txt" | ./hostsblock/hostsblock - > ./LatvianList+EasyList/hosts
         curl -s "https://easylist-downloads.adblockplus.org/liste_ar+liste_fr+easylist.txt"  | ./hostsblock/hostsblock - > ./ListeAR+ListeFR+EasyList/hosts
         curl -s "https://easylist-downloads.adblockplus.org/liste_fr+easylist.txt" | ./hostsblock/hostsblock - > ./ListeFR+EasyList/hosts
         curl -s "https://easylist-downloads.adblockplus.org/rolist+easylist.txt" | ./hostsblock/hostsblock - > ./ROList+EasyList/hosts
         curl -s "https://easylist-downloads.adblockplus.org/ruadlist+easylist.txt" | ./hostsblock/hostsblock - > ./RuAdList+EasyList/hosts
         
         
         sudo rm -rf  easylistschina
         sudo rm -rf  indonesianadblockrules
         sudo rm -rf  abpvn
         sudo rm -rf  listefr
         sudo rm -rf  ruadlist
         sudo rm -rf hostsblock
        env:
          key: ${{ secrets.key }} # if run.py requires passwords..etc, set it as secrets
      - name: Commit files # transfer the new html files back into the repository
        run: |
         git config --local user.name "Update"
         git add .
         git commit -m "Updating the hosts file"
      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         force: true
